"""No-LLM pipeline search: greedy coordinate search over a library of generic pipeline operations.

This is the "TabFM+" style baseline from the paper (generic cleaning, feature crosses, SVD, context views,
calibration) run as a search instead of fixed presets. It needs no API and no GPU beyond the frozen model, so it
is the fallback when no LLM is available and the control for "how much of the gain comes from domain knowledge".

Each candidate is a config dict rendered into a pipeline.py (``render_pipeline``) and scored with ``tabfm-eval``
exactly like an agent's candidate. Search: start from the identity config; for every knob try each alternative
value on top of the current best; keep it if the CV score improves; repeat until the eval budget is spent or a
full sweep gives no improvement.
"""
from __future__ import annotations

import json
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

TEMPLATE = '''"""Pipeline generated by tabfm_auto.agent.heuristic (no LLM). CONFIG lists the operations that are on."""
import numpy as np
import pandas as pd

CONFIG = __CONFIG__
MODEL_KWARGS = CONFIG.get("model_kwargs", {})
_STATE = {}


def _num_cols(X):
    return [c for c in X.columns if pd.api.types.is_numeric_dtype(X[c])]


def preprocess(X_train, y_train, X_test):
    X_train, X_test = X_train.copy(), X_test.copy()
    y = pd.Series(np.asarray(y_train, dtype=float)) if CONFIG.get("regression") else y_train
    if CONFIG.get("sentinel_to_nan"):
        for c in _num_cols(X_train):
            v = X_train[c]
            for s in (0, -1, 999, 9999, -999):
                if (v == s).mean() > 0.2 and v.nunique() > 10:
                    X_train.loc[X_train[c] == s, c] = np.nan
                    X_test.loc[X_test[c] == s, c] = np.nan
    if CONFIG.get("winsorize"):
        for c in _num_cols(X_train):
            lo, hi = X_train[c].quantile(0.005), X_train[c].quantile(0.995)
            X_train[c] = X_train[c].clip(lo, hi)
            X_test[c] = X_test[c].clip(lo, hi)
    if CONFIG.get("drop_constant"):
        keep = [c for c in X_train.columns if X_train[c].nunique(dropna=False) > 1]
        X_train, X_test = X_train[keep], X_test[keep]
    if CONFIG.get("regression") and CONFIG.get("target_transform") == "log1p":
        if (y >= 0).all():
            _STATE["shift"] = 0.0
            y = np.log1p(y)
            _STATE["inv"] = "log1p"
    return X_train, y, X_test


def engineer(X_train, y_train, X_test):
    X_train, X_test = X_train.copy(), X_test.copy()
    num = _num_cols(X_train)
    if CONFIG.get("count_encode"):
        for c in list(X_train.columns):
            v = pd.concat([X_train[c], X_test[c]])
            if v.nunique() > 20 and (not pd.api.types.is_float_dtype(v) or (v.dropna() % 1 == 0).all()):
                cnt = v.value_counts()
                X_train[f"{c}__count"] = X_train[c].map(cnt).fillna(0).astype(float)
                X_test[f"{c}__count"] = X_test[c].map(cnt).fillna(0).astype(float)
    if CONFIG.get("log_skewed"):
        for c in num:
            v = X_train[c]
            if (v.dropna() > 0).all() and abs(v.skew()) > 2:
                X_train[f"log_{c}"] = np.log(X_train[c])
                X_test[f"log_{c}"] = np.log(X_test[c])
    k = CONFIG.get("crosses_top_k", 0)
    if k and len(num) >= 2:
        top = _top_features(X_train[num], y_train, k)
        for i in range(len(top)):
            for j in range(i + 1, len(top)):
                a, b = top[i], top[j]
                X_train[f"{a}_x_{b}"] = X_train[a] * X_train[b]
                X_test[f"{a}_x_{b}"] = X_test[a] * X_test[b]
                X_train[f"{a}_div_{b}"] = X_train[a] / (X_train[b].abs() + 1e-9)
                X_test[f"{a}_div_{b}"] = X_test[a] / (X_test[b].abs() + 1e-9)
    n_svd = CONFIG.get("svd_components", 0)
    if n_svd and X_train.shape[1] > n_svd * 4:
        from sklearn.decomposition import TruncatedSVD
        from sklearn.preprocessing import StandardScaler
        cols = _num_cols(X_train)
        sc = StandardScaler().fit(X_train[cols].fillna(0))
        svd = TruncatedSVD(n_svd, random_state=0).fit(sc.transform(X_train[cols].fillna(0)))
        for i, (tr, te) in enumerate(zip(svd.transform(sc.transform(X_train[cols].fillna(0))).T,
                                         svd.transform(sc.transform(X_test[cols].fillna(0))).T)):
            X_train[f"svd_{i}"] = tr
            X_test[f"svd_{i}"] = te
    if CONFIG.get("prune_to", 0) and X_train.shape[1] > CONFIG["prune_to"]:
        keep = _top_features(X_train[_num_cols(X_train)], y_train, CONFIG["prune_to"])
        X_train, X_test = X_train[keep], X_test[keep]
    return X_train, X_test


def _top_features(X, y, k):
    try:
        from sklearn.feature_selection import mutual_info_classif, mutual_info_regression
        f = mutual_info_regression if CONFIG.get("regression") else mutual_info_classif
        mi = f(X.fillna(X.median()), y, random_state=0)
        order = np.argsort(-mi)
    except Exception:
        order = np.argsort(-X.var().fillna(0).to_numpy())
    return [X.columns[i] for i in order[:k]]


def sample(X_train, y_train, X_test, max_rows):
    n = len(X_train)
    rng = np.random.default_rng(0)
    views = []
    if CONFIG.get("balanced_views") and not CONFIG.get("regression"):
        y = pd.Series(np.asarray(y_train))
        counts = y.value_counts()
        if counts.min() / counts.max() < 0.3:
            views.append(np.arange(n))
            minority = y[y != counts.idxmax()].index.to_numpy()
            majority = y[y == counts.idxmax()].index.to_numpy()
            take = min(len(majority), 2 * len(minority))
            views.append(np.sort(np.concatenate([minority, rng.choice(majority, take, replace=False)])))
            return [v[:max_rows] for v in views]
    k = CONFIG.get("random_views", 1)
    if n <= max_rows and k == 1:
        return [np.arange(n)]
    return [np.sort(rng.choice(n, min(n, max_rows), replace=False)) for _ in range(max(k, 1))]


def postprocess(pred, y_train_orig, X_test):
    if CONFIG.get("regression"):
        if _STATE.get("inv") == "log1p":
            pred = np.expm1(np.asarray(pred, dtype=float))
        return pred
    P = pred.to_numpy(dtype=float) if hasattr(pred, "to_numpy") else np.asarray(pred, dtype=float)
    if CONFIG.get("prior_correction"):
        cols = list(pred.columns)
        prior = pd.Series(y_train_orig).value_counts(normalize=True).reindex(cols).fillna(1e-6).to_numpy()
        z = np.log(np.clip(P, 1e-9, 1)) + np.log(prior / np.clip(P.mean(0), 1e-9, 1))
        z -= z.max(1, keepdims=True)
        P = np.exp(z)
        P /= P.sum(1, keepdims=True)
    t = CONFIG.get("temperature", 1.0)
    if t != 1.0:
        z = np.log(np.clip(P, 1e-9, 1)) / t
        z -= z.max(1, keepdims=True)
        P = np.exp(z)
        P /= P.sum(1, keepdims=True)
    return pd.DataFrame(P, columns=list(pred.columns))
'''

# knob -> alternative values tried on top of the current best (identity = first value / absent)
KNOBS: dict[str, list[Any]] = {
    "sentinel_to_nan": [True],
    "winsorize": [True],
    "drop_constant": [True],
    "count_encode": [True],
    "log_skewed": [True],
    "crosses_top_k": [3, 5],
    "svd_components": [8, 16],
    "prune_to": [64],
    "balanced_views": [True],
    "random_views": [3],
    "prior_correction": [True],
    "temperature": [0.8, 1.25],
    "target_transform": ["log1p"],
    "model_kwargs": [{"n_estimators": 8}],
}
CLASSIFICATION_ONLY = {"balanced_views", "prior_correction", "temperature"}
REGRESSION_ONLY = {"target_transform"}


def render_pipeline(config: dict[str, Any]) -> str:
    return TEMPLATE.replace("__CONFIG__", repr(config))  # python literal, not JSON (True/False/None)


def _eval(ws: Path, timeout_s: int) -> dict[str, Any]:
    subprocess.run([sys.executable, "-m", "tabfm_auto.harness.cli", "--workspace", str(ws)], cwd=str(ws),
                   capture_output=True, text=True, timeout=timeout_s + 60, check=False)
    recs = [json.loads(line) for line in (ws / "evals.jsonl").read_text().splitlines() if line.strip()]
    return recs[-1] if recs else {"status": "error", "score": None}


def run_heuristic_search(ws: Path, task_type: str, budget_evals: int, budget_minutes: int, log: Any = None,
                         eval_timeout_s: int = 900) -> dict[str, Any]:
    """Greedy search; leaves ws/pipeline.py equal to the best config. Returns a summary dict."""
    t0 = time.time()
    regression = task_type == "regression"
    base: dict[str, Any] = {"regression": regression}
    (ws / "pipeline.py").write_text(render_pipeline(base))
    recs = [json.loads(line) for line in (ws / "evals.jsonl").read_text().splitlines()] if (ws / "evals.jsonl").exists() else []
    if not recs:  # P0 of this template (equals the identity pipeline functionally)
        recs.append(_eval(ws, eval_timeout_s))
    best_score = recs[-1].get("score") if recs[-1].get("status") == "ok" else float("inf")
    best_cfg = dict(base)
    trace = [{"config": dict(base), "score": best_score}]
    knobs = [(k, vals) for k, vals in KNOBS.items()
             if not (regression and k in CLASSIFICATION_ONLY) and not (not regression and k in REGRESSION_ONLY)]
    improved = True
    n_evals = len(recs)
    while improved and n_evals < budget_evals and (time.time() - t0) < budget_minutes * 60:
        improved = False
        for knob, values in knobs:
            for v in values:
                if n_evals >= budget_evals or (time.time() - t0) >= budget_minutes * 60:
                    break
                if best_cfg.get(knob) == v:
                    continue
                cand = dict(best_cfg)
                cand[knob] = v
                (ws / "pipeline.py").write_text(render_pipeline(cand))
                r = _eval(ws, eval_timeout_s)
                n_evals += 1
                s = r.get("score") if r.get("status") == "ok" else None
                trace.append({"config": cand, "score": s, "error": r.get("error")})
                if log is not None:
                    log.event("heuristic_eval", knob=knob, value=v, score=s, best=best_score, error=r.get("error"))
                if s is not None and s < best_score - 1e-12:
                    best_score, best_cfg, improved = s, cand, True
    (ws / "pipeline.py").write_text(render_pipeline(best_cfg))
    (ws / "NOTES.md").write_text("Heuristic (no-LLM) greedy search. Best config:\n" + json.dumps(best_cfg, indent=1) + "\n")
    return {"harness": "heuristic", "best_config": best_cfg, "best_cv": best_score, "n_evals": n_evals,
            "elapsed_s": round(time.time() - t0, 1), "trace": trace}
